### ISSUE TITLE
The java version is obviously cheating

### ISSUE THREAD

**Issue by arloan** [andreaferretti/kmeans#35]
The java version of this k-means benchmark code is obviously cheating compared to other object-oriented language versions, i.e the ruby one. Since I'm not a language expert, I did not check other language versions other than java and ruby.
- The java version reused the Centroids array between iterations for every run loop, while the ruby version re-allocates.
- The java version uses `addToThis()` method to avoid allocating new Point object, while the ruby version allocates new Point object on every `+` operator calling. This makes the ruby version allocating Point object about 100,000 × 15 more times than the ruby version for every run. The `divideToThis()` does the same thing, but is fare less important then the former.

**Comment by fralken** [comment]
The java version correctly initialises centroids for every run loop, and reusing objects doesn't mean cheating, but rather managing resources wisely.
