### ISSUE TITLE
How can I increase the size of dataset ?

### ISSUE THREAD

**Issue by spate141** [andreaferretti/kmeans#52]
I can see the data available in points.json, is there any way I can increase the size of this file with adding more points ?

**Comment by andreaferretti** [comment]
See [here](https://github.com/andreaferretti/kmeans/blob/44cb32cca718041c6c25fc0327ee34f66bf6d280/scala/src/main/scala/kmeans/Generator.scala) for how the points were generated

**Comment by spate141** [comment]
Thanks, I can see how the points are generating. Thing is that I have little over no knowledge of Scala. If you can just give me some information on how I can run this Generator.scala file, It would be so much easy for me to go ahead and complete my remaining task.

**Comment by spate141** [comment]
Amm.. after some scala crash course, I get it working. Thanks.

**Comment by andreaferretti** [comment]
Great! :-)
