### ISSUE TITLE
libjansson error?

### ISSUE THREAD

**Issue by spate141** [andreaferretti/kmeans#53]
Hey, So I am using AWS cuda instance and trying to run cuda version. AWS Instance has everything installed and I have installed jansson from `http://shellgui-docs.readthedocs.io/en/latest/gettingstarted.html` successfully. Still I am getting this error. Any suggestion ? Thanks

`./kmeans.out: error while loading shared libraries: libjansson.so.4: cannot open shared object file: No such file or directory`

edit: 

> echo $LD_LIBRARY_PATH

`/root/lib/`

and /root/lib/ has following files:
`libjansson.a  libjansson.la  libjansson.so  libjansson.so.4  libjansson.so.4.9.0  pkgconfig`

**Comment by andreaferretti** [comment]
Did you use cmake as described in the README?

**Comment by spate141** [comment]
Yes, I did. 
Anyway, after some playing around its now working. I guess the problem was in setting LD_LIBRARY_PATH in current environment. 
Thanks.
